### PR TITLE
Dir constant

### PR DESCRIPTION
**Pull request by MathiasReker**

### CODE REVIEW

**Comment by rblaurin** [comment]
I still don't know if we can use the __DIR__ constant in modules. The module validator says it is forbidden. Why?

**Comment by Matt75** [comment]
> I still don't know if we can use the **DIR** constant in modules. The module validator says it is forbidden. Why?

Due to compatibility checker with PrestaShop 1.5 which require PHP 5.2 
DIR constant has been introduced in PHP 5.3
I thinks it's allowed if you use `PrestaShop 1.7 compliant` option because it require PHP 5.6

**Comment by MathiasReker** [comment]
You can use it for PS 1.7 But when possible you should rather use PrestaShop constants: https://blog.floriancourgey.com/2018/04/constants-and-variables-for-prestashop/

**Comment by PierreRambaud** [comment]
So we can use this const because of https://github.com/PrestaShop/ps_legalcompliance/blob/master/ps_legalcompliance.php#L83, or 1.7.3 was PHP5.2 compliant? 🤔

**Comment by Matt75** [comment]
PHP 5.4 for PrestaShop 1.7.3 https://github.com/PrestaShop/PrestaShop/blob/335851e5523b19aac49a65e5173414cfbc7df083/composer.json#L6

**Comment by PierreRambaud** [comment]
Thanks @Matt75, I close this PR, sorry @MathiasReker  :/

**Comment by rblaurin** [comment]
@PierreRambaud Why? PrestaShop 1.7.3 requires PHP 5.4, and __DIR__ was introduced in 5.3, right?

**Comment by PierreRambaud** [comment]
You're right, maybe to tired ><

**Comment by PierreRambaud** [comment]
Thanks @MathiasReker  and sorry for the mistake 🙄

**Pull request merged**
