### PR TITLE
Do not link privacy policy in the final opt-in

### PR DESCRIPTION
**Pull request by maximebiloe**
http://forge.prestashop.com/browse/BOOM-1201

### CODE REVIEW

**Comment by vTerenti** [comment]
OK for me!

**Comment by Nobodaddy** [comment]
Hmmm ...
As PrestaShop includes a dummy text for both this condition will always be true:
_ if ((int) $cms_page_conditions_associated->id_cms > 0 && (int) $cms_page_revocation_associated->id_cms > 0)_

**Comment by maximebiloe** [comment]
It is if the user keep the default date but not if he deletes the page.

**Comment by Nobodaddy** [comment]
You must be kidding.

**Pull request merged**
